version: '3'

services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    command: "irb"
    volumes:
      - .:/book_app
      - gem_data:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
    tty: true
    stdin_open: true

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/book_app/public
      - tmp-data:/book_app/tmp
    ports:
      - 80:80
    depends_on:
      - app

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none

volumes:
  mysql_data:
  gem_data:
  public-data:
  tmp-data: