version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.3
    working_directory: ~/book_app
    steps:
      - checkout
      - ruby/install-deps

commands:
  install_bundler:
    description: Bundler install
    steps:
      - run: gem install bundler -v 2.2.21

  test:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.7.3
      - image: circleci/mysql:5.6
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: book_app_test
          MYSQL_USER: root
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      BUNDLER_VERSION: 2.2.21
      RAILS_ENV: test
    working_directory: ~/book_app
    steps:
      - checkout
      - ruby/install-deps
      - install_bundler
      - run: mv config/database.yml.ci config/database.yml
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: Rubocop
          command: bundle exec rubocop
      - run:
          name: Rspec
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES
      - ruby/rspec-test
      - ruby/rubocop-check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build