version: 2.1

executors:
  default_container:
    docker:
      - image: circleci/ruby:2.7.3
        environment:
          BUNDLE_JOBS: "3"
          BUNDLE_RETRY: "3"
          BUNDLER_VERSION: 2.2.21
          RAILS_ENV: test
      - image: circleci/mysql:5.6
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: book_app_test
    working_directory: ~/book_app

commands:
  install_bundler:
    description: Bundler install
    steps:
      - run: gem install bundler -v 2.2.21

orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    executor:
      name: default_container
    steps:
      - checkout
      - ruby/install-deps

  rspec:
    executor:
      name: default_container
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Bundler install
          command: gem install bundler -v 2.2.21
      - run:
          name: Watting stand up database
          command: |
            dockerize -wait \
            tcp://127.0.0.1:3306 -timeout 120s
      # Database setup
      - run: mv config/database.yml.ci config/database.yml
      - run:
          name: Database setup
          command: |
            bundle exec rails db:create
            bundle exec rails db:schema:load
      - run:
          name: Rspec
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"
            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
      - ruby/rspec-test
      - ruby/rubocop-check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - rspec:
          requires:
            - build